### ISSUE TITLE
Blank screen on serve

### ISSUE THREAD

**Issue by samratarmas** [DominikPieper/nx-extensions#10]
Hello Dominik,
Really appreciate your work on this project. I encountered the following error when serving using nx serve: `GET http://localhost:3333/build/client-app.esm.js net::ERR_ABORTED 404 (Not Found)`

When checking the dist folder I can see that the file name is always built as `app.esm.js` by stencil, and hence the file `client-app.esm.js` will not be found. 

`client-app` is an arbitrary nx app name for demo purposes.

**Comment by samratarmas** [comment]
Things work great when the nx app name is just `app` because it will then match the `app.esm.js` script.

**Comment by DominikPieper** [comment]
Hello Samrat,
thanks for reporting. There was a wrong url generation.
The next release will fix it. :-)

Best regards,
Dominik
